<a href="https://colab.research.google.com/github/Parthiv-Kola/Crop-Recommendation/blob/main/pytorch_fundamentals/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


### Creating a Tensor

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
# to get it back as an integer
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
# Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
matrix.ndim

2

In [14]:
matrix[0]

tensor([7, 8])

In [15]:
matrix[1]

tensor([ 9, 10])

In [16]:
matrix.shape

torch.Size([2, 2])

In [17]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])